services:
  website-creator:
    build: .
    image: website-creator
    container_name: website-creator
    ports:
      - "80:8080"    # Flask UI (host:80 -> container:8080)
      - "5000:5000"  # Apache2 default site
      - "8000-9000:8000-9000"  # Website ports
    volumes:
      - /opt/website-creator:/var/www/html
      - /opt/website-creator/ports.txt:/app/ports.txt
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - SERVER_IP=${SERVER_IP}  # Required: set in .env or environment
    restart: unless-stopped
